[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairopen_contracts/src",
    "./lib/cairo_contracts/src",
    "./lib/bal7hazar_contracts/src",
    "src",
]

[contracts]
CarbonableProxy = ["src/proxy/proxy.cairo"]
CarbonableBadge = ["src/badge/badge.cairo"]
CarbonableMinter = ["src/minter/minter.cairo"]

[test]
target = ["tests"]

[profile.testnet.project]
network = "testnet"
private-key-path = "./.env"
account-address = "0x063675fa1ecea10063722e61557ed7f49ed2503d6cdd74f4b31e9770b473650c"
block-explorer = "starkscan"

[profile.mainnet.project]
network = "mainnet"
